/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EbookRouteImport } from './routes/ebook'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as IndexRouteImport } from './routes/index'

const EbookRoute = EbookRouteImport.update({
  id: '/ebook',
  path: '/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/ebook': typeof EbookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/ebook': typeof EbookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/ebook': typeof EbookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout-success' | '/ebook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout-success' | '/ebook'
  id: '__root__' | '/' | '/checkout-success' | '/ebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EbookRoute: typeof EbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ebook': {
      id: '/ebook'
      path: '/ebook'
      fullPath: '/ebook'
      preLoaderRoute: typeof EbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EbookRoute: EbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
